---
abstract: 'Perl extention to do something'
author:
  - 'Nishibayashi Takuji E<lt>takuji31@gmail.comE<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0.06
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Try-Lite-Prefix
no_index:
  directory:
    - inc
requires:
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
